gpu-operator:
  cdi:
    enabled: false
    default: false

  nfd:
    enabled: true

  devicePlugin:
    enabled: true
    config:
      create: false
      name: time-slicing-config-all
      default: "time-slicing-config-all" 

  driver:
    enabled: false
    nvidiaDriverCRD:
      enabled: false
    version: "580.126.09"

  migManager:
    enabled: false
    config:
      create: false
      default: all-disabled
      name: default-mig-parted-config

  toolkit:
    enabled: false

  dcgm:
    enabled: false

  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true