apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mail

labels:
  - pairs:
      app: dovecot

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - certificate.yaml
  - secrets.yaml
  - DNSEndpoint.yaml
  - backup-schedule.yaml

