apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
#  - pvc.yaml
  - model-script.yaml
  - deployment.yaml
  - service.yaml
  - init-job.yaml
  - ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app: speaches

