apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kokoro-ingress
  annotations:
    ingressClassName: traefik
    cert-manager.io/cluster-issuer: nf-lab
    cert-manager.io/private-key-rotation-policy: Always
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/target: traefik.k3s.nf.lab
spec:
  rules:
  - host: kokoro.k3s.nf.lab
    http:
      paths:
      - backend:
          service:
            name: kokoro
            port:
              number: 8880
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kokoro.k3s.nf.lab
    secretName: kokoro-tls